[files]
extend-exclude = ["**/CHANGELOG.md", "CHANGELOG.md"]

[default.extend-words]
ba = "ba"
Ue = "Ue"
TrUe = "TrUe"
ded = "ded"
DEMOG = "DEMOG"
decod = "decod"
Decod = "Decod"
unparseable = "unparseable"
NAMEs = "NAMEs"
mis = "mis"
