#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret names set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "iMedNet EDC Environment & Developer Workspace Setup"

# ── Stage 1: Tooling & PATH Verification ──────────────────────────────────
stage "Tooling & PATH Verification"
say "Checking required developer tooling (Python, uv, and GitHub CLI)..."

# 1. Check Python >= 3.10
PYTHON_BIN=""
if command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN="python3"
elif command -v python >/dev/null 2>&1; then
  PYTHON_BIN="python"
fi

if [[ -n "$PYTHON_BIN" ]]; then
  PY_VER=$("$PYTHON_BIN" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || echo "0.0")
  say "Found Python $PY_VER ($PYTHON_BIN)"
else
  warn "Python not found! Please install Python 3.10+."
fi

# 2. Check uv and locate if not in PATH
if ! command -v uv >/dev/null 2>&1; then
  warn "'uv' is not currently in your system PATH."
  say "Searching common install locations..."

  FOUND_UV=""
  # Common Windows locations (Git Bash / MSYS2 syntax and Windows syntax)
  for candidate in \
    "$APPDATA/Python/Python"*/Scripts/uv.exe \
    "$HOME/AppData/Roaming/Python/Python"*/Scripts/uv.exe \
    "$HOME/.cargo/bin/uv.exe" \
    "$HOME/.cargo/bin/uv" \
    "$HOME/.local/bin/uv" \
    "/c/Python"*/Scripts/uv.exe \
    "/c/Users/$USER/AppData/Roaming/Python/Python"*/Scripts/uv.exe \
    "/opt/homebrew/bin/uv"; do
    if compgen -G "$candidate" >/dev/null 2>&1; then
      for match in $candidate; do
        if [[ -x "$match" || -f "$match" ]]; then
          FOUND_UV="$match"
          break 2
        fi
      done
    fi
  done

  if [[ -n "$FOUND_UV" ]]; then
    UV_DIR=$(dirname "$FOUND_UV")
    export PATH="$UV_DIR:$PATH"
    say "✓ Discovered uv at: $FOUND_UV"
    say "  Temporarily added $UV_DIR to PATH for this session."
    note "To add permanently on Windows: setx PATH \"%PATH%;$UV_DIR\""
    note "To add permanently on Unix/macOS: echo 'export PATH=\"$UV_DIR:\$PATH\"' >> ~/.bashrc"
  else
    say "uv could not be found automatically."
    if confirm "Install uv now via pip?"; then
      "$PYTHON_BIN" -m pip install --user uv || warn "Failed to install uv via pip."
      # Try finding again
      for candidate in "$APPDATA/Python/Python"*/Scripts/uv.exe "$HOME/AppData/Roaming/Python/Python"*/Scripts/uv.exe; do
        if compgen -G "$candidate" >/dev/null 2>&1; then
          for match in $candidate; do
            UV_DIR=$(dirname "$match")
            export PATH="$UV_DIR:$PATH"
            say "✓ Installed and added uv to PATH: $match"
            break 2
          done
        fi
      done
    else
      note "Install uv manually: https://docs.astral.sh/uv/getting-started/installation/"
    fi
  fi
else
  say "✓ 'uv' is available in PATH ($(uv --version 2>/dev/null || echo 'uv ready'))"
fi

# 3. Check GitHub CLI
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    say "✓ GitHub CLI (gh) is installed and authenticated."
  else
    note "GitHub CLI (gh) is installed but not authenticated (run 'gh auth login' to sync secrets)."
  fi
else
  note "GitHub CLI (gh) not detected; CI secret synchronization will be skipped."
fi
pause "Press Enter to proceed to encoding configuration..."

# ── Stage 2: Windows Console & UTF-8 Encoding ─────────────────────────────
stage "Console & UTF-8 Encoding"
say "Configuring UTF-8 console encoding."
note "On Windows, consoles default to legacy codepages (cp1252), which can cause"
note "charmap UnicodeEncodeError / UnicodeDecodeError when tools emit emojis or UTF-8 text."
say "Setting PYTHONUTF8=1 and PYTHONIOENCODING=utf-8 in .env..."
write_env PYTHONUTF8 "1"
write_env PYTHONIOENCODING "utf-8"
export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8
note "Tip: In PowerShell, also add \$env:PYTHONUTF8 = \"1\" to your \$PROFILE."
pause "Press Enter to proceed to workspace dependency sync..."

# ── Stage 3: Workspace Dependency Synchronization ─────────────────────────
stage "Workspace Dependency Sync"
say "Synchronizing the monorepo workspace virtual environment (.venv)..."
say "This installs all 5 packages in editable mode along with dev (pytest, ruff, mypy) and docs dependencies."
if confirm "Run 'uv sync --extra dev --extra docs' now?"; then
  if command -v uv >/dev/null 2>&1; then
    say "Running 'uv sync --extra dev --extra docs'..."
    if uv sync --extra dev --extra docs; then
      say "✓ Workspace dependencies synchronized successfully."
    else
      warn "uv sync encountered issues. You can re-run 'uv sync --extra dev --extra docs' later."
    fi
  else
    warn "uv is not available. Please install uv and run 'uv sync --extra dev --extra docs'."
  fi
else
  say "Skipping dependency sync. Run 'uv sync --extra dev --extra docs' when ready."
fi
pause "Press Enter to proceed to EDC credentials configuration..."

# ── Stage 4: EDC Endpoint & Authentication ────────────────────────────────
stage "iMedNet EDC Endpoint & Authentication"
say "Specify the base API URL for your iMedNet EDC instance."
say "Default is production: https://edc.prod.imednetapi.com"
ask IMEDNET_BASE_URL "Enter IMEDNET_BASE_URL [press Enter for default]:"
if [[ -z "$IMEDNET_BASE_URL" ]]; then
  IMEDNET_BASE_URL="https://edc.prod.imednetapi.com"
fi
write_env IMEDNET_BASE_URL "$IMEDNET_BASE_URL"

step "Opening your EDC portal in the browser..."
open_url "$IMEDNET_BASE_URL"
pause "Log in to the EDC portal, then press Enter..."

say "Retrieve your API credentials from your iMedNet EDC account."
step "In the EDC portal, navigate to User Profile / Settings → API Access."
step "Copy the API Key and Security Key."
note "Per repository rules, keys are entered masked and stored only in git-ignored .env."
ask_secret IMEDNET_API_KEY "Paste your IMEDNET_API_KEY:"
write_env IMEDNET_API_KEY "$IMEDNET_API_KEY"
ask_secret IMEDNET_SECURITY_KEY "Paste your IMEDNET_SECURITY_KEY:"
write_env IMEDNET_SECURITY_KEY "$IMEDNET_SECURITY_KEY"

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Sync these credentials to GitHub Actions secrets via gh?"; then
    set_secret IMEDNET_API_KEY "$IMEDNET_API_KEY"
    set_secret IMEDNET_SECURITY_KEY "$IMEDNET_SECURITY_KEY"
    set_var IMEDNET_BASE_URL "$IMEDNET_BASE_URL"
  fi
fi

# ── Stage 5: Study Configuration & Safety Guardrails ──────────────────────
stage "Study Configuration & Safety Guardrails"
say "Configure a default study key for local queries, CLI operations, and smoke tests."
step "In the EDC portal, look at the Study list for your trial identifier."
ask IMEDNET_STUDY_KEY "Enter default IMEDNET_STUDY_KEY (or press Enter to discover dynamically):"
if [[ -n "$IMEDNET_STUDY_KEY" ]]; then
  write_env IMEDNET_STUDY_KEY "$IMEDNET_STUDY_KEY"
else
  say "No static study key set; SDK and scripts will discover study keys dynamically."
fi

say "Configure runtime safety guardrails:"
if confirm "Allow write/mutation operations during tests (IMEDNET_ALLOW_MUTATION=1)?"; then
  write_env IMEDNET_ALLOW_MUTATION "1"
else
  write_env IMEDNET_ALLOW_MUTATION "0"
fi
if confirm "Enable strict schema validation (IMEDNET_STRICT_MODE=1)?"; then
  write_env IMEDNET_STRICT_MODE "1"
else
  write_env IMEDNET_STRICT_MODE "0"
fi

# ── Stage 6: SDK Self-Test & Verification ─────────────────────────────────
stage "SDK Self-Test & Verification"
say "Verifying that your .env file can be loaded by the SDK..."

if command -v uv >/dev/null 2>&1; then
  uv run python -c "from imednet.config import load_config; cfg = load_config(); print('  ✓ Config loaded successfully. Base URL:', cfg.base_url)" || warn "Could not run python check via uv. Run 'uv sync' to install dependencies."
  uv run imednet --help >/dev/null 2>&1 && say "  ✓ imednet CLI is installed and accessible." || true
elif command -v python >/dev/null 2>&1; then
  python -c "from imednet.config import load_config; cfg = load_config(); print('  ✓ Config loaded successfully. Base URL:', cfg.base_url)" || warn "Could not run python check. Ensure virtual environment is activated."
fi

say ""
say "Common Developer Commands Cheatsheet:"
say "  • Run full CI quality gate:   uv run ruff check . && uv run ruff format --check . && uv run mypy packages/core/src/imednet"
say "  • Run test suite:             uv run pytest -q"
say "  • Build documentation:        uv run python scripts/build_docs.py"
say "  • Run security audit:         uv run --with pip-audit pip-audit -s osv"
say "  • Launch CLI:                 uv run imednet --help"
pause "Press Enter to finish setup..."

finish
